

package com.crow.zipline.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link com.crow.zipline.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-plugin/testData/zipline")
@TestDataPath("$PROJECT_ROOT")
public class ZiplineServiceTestGenerated extends AbstractZiplineServiceTest {
  @Test
  public void testAllFilesPresentInZipline() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/zipline"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
  }

  @Test
  @TestMetadata("ZiplineService.kt")
  public void testZiplineService() {
    runTest("compiler-plugin/testData/zipline/ZiplineService.kt");
  }
}
